PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/02ab0cd149f464d5bc4acfaefe23a430c585da72

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/7fffab1610d2ea08a95383febd0579e0037b6b51) in current PX4/master (d29344cb9c59f5b2798a21849de3637d38d7fe28)
https://github.com/PX4/NuttX/compare/7fffab1610d2ea08a95383febd0579e0037b6b51...02ab0cd149f464d5bc4acfaefe23a430c585da72

02ab0cd149 (HEAD, origin/master) stm32: Fix typos, wrong comments, and nxstyle.
31332904dd Added support to crashdump for rx65n on sbram
40eb87d8b4 boards: maix-bit: Update instructions for kostest
ad9db974cb mm: Fix heap corruption in protected build
79589eca1a cxd56: replace Sony return values
ecc4939453 cxd56: fix volume setting and improve volume range
36e756a915 cxd56: add support for pause and resume
7a83177419 cxd56: disable unused audio effects
d9d720b296 audio: nxstyle fixes for core and drivers
76c47f6b21 libc: audio: nxstyle fixes

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/2749e6467bd69638d246a33bfa55d89e684475df

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/95e105548a2037f42bf2f13b214ae083b921ff03) in current PX4/master (d29344cb9c59f5b2798a21849de3637d38d7fe28)
https://github.com/PX4/NuttX-apps/compare/95e105548a2037f42bf2f13b214ae083b921ff03...2749e6467bd69638d246a33bfa55d89e684475df

2749e646 (HEAD -> master, origin/master) system: nxplayer & nxrecorder: nxstyle fixes
1697c649 examples: nxwidget: nxstyle fixes
c9eaf0be examples: i2sloop: nxstyle fixes
3cdb8107 examples: i2schar: nxstyle fixes
989988fa build.yml: Remove -G from cibuild.sh command line
f18b283e nshlib: add printf command to README.TXT
63288eb8 fix apps/include/graphics/nxwidgets/cwidgetcontrol.hxx:550:20: error: ‘m_xyinput’ was not declared in this scope
68ed2a2a build.yaml: Change arm-11 to arm-12
0c84e22a example: Remove all APPNAME from Makefile
4431d770 .gitignore: Add more entries found during prcheck testing